"""Usuario

Revision ID: 47d109c81683
Revises: ee6ba2516fbd
Create Date: 2024-02-13 14:13:13.201486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47d109c81683'
down_revision: Union[str, None] = 'ee6ba2516fbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('birthdate', sa.TIMESTAMP(), nullable=True))
    op.add_column('users', sa.Column('term_conditions', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.TIMESTAMP(), nullable=True))
    op.add_column('users', sa.Column('date_joined', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'date_joined')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'term_conditions')
    op.drop_column('users', 'birthdate')
    op.drop_column('users', 'role')
    op.drop_column('users', 'image')
    # ### end Alembic commands ###
